### ISSUE TITLE
Screen stays on unless explicitly shut off

### ISSUE THREAD

**Issue by raij** [7yl4r/AvatarWallpaper#30] opened 2013-03-12 20:34 UTC
I think the app is holding a wakelock, which keeps the screen on indefinitely.  This significantly affects battery life.

**Comment by 7yl4r** [comment] 2013-03-13 04:22
I haven't seen any wakelock code in there, and the manifest doesn't give the permission. 

I also don't see this on my phone...

You have the Samsung Galaxy S III/SCH-I535 running android 4._._ right? I was unable to reproduce this using another phone running android 4.\* either, so it may be a device-specific issue.

**Comment by raij** [comment] 2013-03-13 15:04
Yes, that's my phone.  I'm running a battery debug app to see who has that wake lock.

---

Andrew Raij, Ph.D.
Assistant Professor, Department of Electrical Engineering
Department of Computer Science and Engineering (courtesy)
University of South Florida
E-mail: raij@usf.edumailto:raij@usf.edu
Web: http://www.eng.usf.edu/~raij

On Mar 13, 2013, at 12:22 AM, Tylar <notifications@github.com<mailto:notifications@github.com>> wrote:

I haven't seen any wakelock code in there, and the manifest doesn't give the permission.

I also don't see this on my phone...

You have the Samsung Galaxy S III/SCH-I535 running android 4._._ right? I was unable to reproduce this using another phone running android 4.\* either, so it may be a device-specific issue.

**Comment by raij** [comment] 2013-03-14 00:59
I can't replicate this anymore.  My display shuts off as expected today.  So, perhaps we can close this bug.

-Andrew

---

Andrew Raij, Ph.D.
Assistant Professor, Department of Electrical Engineering
Department of Computer Science and Engineering (courtesy)
University of South Florida
E-mail: raij@usf.edumailto:raij@usf.edu
Web: http://www.eng.usf.edu/~raij

On Mar 13, 2013, at 12:22 AM, Tylar <notifications@github.com<mailto:notifications@github.com>> wrote:

I haven't seen any wakelock code in there, and the manifest doesn't give the permission.

I also don't see this on my phone...

You have the Samsung Galaxy S III/SCH-I535 running android 4._._ right? I was unable to reproduce this using another phone running android 4.\* either, so it may be a device-specific issue.

**Comment by 7yl4r** [comment] 2013-03-27 03:46
I've seen multiple different reports of strange behavior like this for services which run constantly. So far as I can tell, there are several similar known issues across different phones and android versions. 

Since there doesn't seem to be anything we can do in our code besides be wary of it, I'm marking it as closed.

**Closed as completed by 7yl4r** 2013-03-27 03:46 UTC
Labels: bug
